# Generated by Django 5.1.3 on 2024-11-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun_terbit', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
                ('kategori', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('cover', models.ImageField(upload_to='covers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
