# Generated by Django 5.1.3 on 2024-11-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sampul',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=225)),
            ],
        ),
    ]
